### ISSUE TITLE
Replace text with icons in main window

### ISSUE THREAD

**Issue by karlosmid** [karlosmid/ExploratoryTestingChromeExtension#4]
In main window, replace text with icons.

Use icons from report page, shown on screenshot.

<img width="841" alt="screen shot 2017-03-29 at 3 25 03 pm" src="https://cloud.githubusercontent.com/assets/777520/24456668/0e991e12-1494-11e7-9bb5-957dfd1f602d.png">

**Comment by karlosmid** [comment]
Icons should be aligned in same row.

**Comment by bkuzmic** [comment]
I've tried to make buttons stay aligned with each other, when counter increases, but didn't make it work. Maybe I can try later.

**Comment by karlosmid** [comment]
:cake:
