### ISSUE TITLE
font awesome page css is over extension css

### ISSUE THREAD

**Issue by karlosmid** [karlosmid/ExploratoryTestingChromeExtension#5]
<img width="1257" alt="screen shot 2017-03-29 at 3 28 01 pm" src="https://cloud.githubusercontent.com/assets/777520/24456798/6d7ec698-1494-11e7-8118-a0b89a243b5d.png">

Is it even possible that extension is always seen, despite of page design?

**Comment by bkuzmic** [comment]
I'm going to implement it using maxZIndex Jquery plugin from:
https://weblog.west-wind.com/posts/2009/Aug/31/Getting-and-setting-max-zIndex-with-jQuery

**Comment by karlosmid** [comment]
@bkuzmic Is ti possible during page shot, put extension window in background, so it is not part of page shot?

**Comment by karlosmid** [comment]
:cake:
